development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tower_dev
  username: root
  pool: 5
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tower
  username: root
  pool: 5
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tower_test
  username: root
  pool: 5



